### ISSUE TITLE
uidProtectedAttributeField

### ISSUE THREAD

**Issue by danjamker** [linkedin/LiFT#6]
Hi, I was wondering where uidProtectedAttributeField is used and is there a better explination of what it is for?

**Comment by sriramvasudevan** [comment]
Hi, the `uidProtectedAttributeField` is used [here](https://github.com/linkedin/LiFT/blob/c8ffc2dceb23ee709932d7fe12975f5da3ff6af6/lift/src/main/scala/com/linkedin/lift/eval/FairnessMetricsUtils.scala#L114). It is meant to be provided when using a top-level driver program like [MeasureDatasetFairnessMetrics](https://github.com/linkedin/LiFT/blob/c8ffc2dceb23ee709932d7fe12975f5da3ff6af6/lift/src/main/scala/com/linkedin/lift/eval/jobs/MeasureDatasetFairnessMetrics.scala) or [MeasureModelFairnessMetrics](https://github.com/linkedin/LiFT/blob/c8ffc2dceb23ee709932d7fe12975f5da3ff6af6/lift/src/main/scala/com/linkedin/lift/eval/jobs/MeasureModelFairnessMetrics.scala). If you are using the lower-level APIs, you may not need to make use of this.

LiFT allows users to specify a dataset of interest and another dataset containing just the protected attribute values. In order to join these two datasets, it needs a join key for both datasets. For the dataset of interest, this is given by the `uidfield` (the 'unique ID field'), and for the protected attribute dataset, this is given by the `uidProtectedAttributeField`.

For example, if your dataset of interest had the fields `(userId, score, label)` and the protected attribute dataset had the fields `(user_id, gender)`, `uidField` would be `userId` and `uidProtectedAttributeField` would be `user_id`.

Hope that helps!
